apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduazureregistry.azurecr.io/frontend-vue # 이미지 주소 변경필요
    newTag: main-20240712064845

commonLabels:
  app: frontend-vue
  environment: dev
