apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-java
  template:
    metadata:
      labels:
        app: backend-java
    spec:
      containers:
      - name: backend-java
        image: eduazureregistry.azurecr.io/backend-java:{{newTag}}
        ports:
        - containerPort: 8080
