name: CI Backend Java

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Docker TAG"
        required: true
        default: "main"
        
jobs:
  build-and-push-backend-java-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Grant execute permission for Gradle wrapper
      run: chmod +x backend-java/gradlew

    - name: Build Java application using Gradle
      working-directory: ./backend-java
      run: ./gradlew build
    
    - name: Get current date and time
      id: datetime
      run: echo "DATE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Get JAR file path
      id: get_jar_path
      run: |
        JAR_PATH=$(find backend-java/build/libs -name '*.jar' | head -n 1)
        if [ -z "$JAR_PATH" ]; then
          echo "No JAR file found!"
          exit 1
        fi
        echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
        echo "Found JAR file: $JAR_PATH"

    - name: Log in to ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.AZURE_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  # 프로젝트 루트를 기준으로 설정
        file: ./gitops/backend-java/Dockerfile  # Dockerfile의 위치를 정확히 지정      
        push: true        
        tags: ${{ secrets.AZURE_URL }}/backend-java:${{ github.event.inputs.name }}-${{ env.DATE_TAG }}
        build-args: |
          JAR_PATH=${{ env.JAR_PATH }}

    - name: Update Kustomize Deployment with New Tag
    # 해당 위치에 내용 추가
      run: |


    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./gitops/backend-java/overlays/dev/kustomization.yaml
        git commit -m "Update backend-java-deployment.yaml with tag $TAG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
