name: CI Backend Java

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend-java-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.AZURE_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and push backend-java Docker image (dev)
      run: |
        TAG=${{ github.sha }}
        docker build -f backend-java/Dockerfile -t ${{ secrets.AZURE_URL }}/backend-java:$TAG ./backend-java
        docker push ${{ secrets.AZURE_URL }}/backend-java:$TAG

    - name: Update Kustomize Deployment with New Tag
      run: |
        TAG="${{ secrets.AZURE_URL }}/backend-java:${{ github.event.inputs.name }}-${{ env.DATE_TAG }}"
        sed -i "s|\(image: backend-java\).*|\1:$TAG|" ./manifest/backend-java/base/deployment.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./manifest/backend-java/base/deployment.yaml
        git commit -m "Update backend-java-deployment.yaml with tag $TAG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
